No1 = int(input("Enter Number 1: "))
No2 = int(input("Enter Number 2: "))
No3 = int(input("Enter Number 3: "))
No4 = int(input("Enter Number 4: "))
No5 = int(input("Enter Number 5: "))
No6 = int(input("Enter Number 6: "))
No7 = int(input("Enter Number 7: "))
No8 = int(input("Enter Number 8: "))

set = { No1, No2, No3, No4, No5, No6, No7, No8}     # we want program print unique numbers ( means not repeat numbers )
print(set)